### ISSUE TITLE
Query regarding missing file

### ISSUE THREAD

**Issue by NIRVANALAN** [stevliu/editnerf#1]
Hi, thanks for sharing this code.

When I tried to run your jupyter file, I find some file missing like there is no ```upsample.py``` in ```ui_utils```, and the jupyter file cannot run with the default configuration. 

Any suggestions and updates?

**Comment by stevliu** [comment]
Hi! Thanks for your interest in our work.

I realized that we changed some names of the setup scripts but forgot to update the jupyter notebook. We've updated the notebook, and `editnerf.ipynb` should run now. 

Please let us know if you run into anything else!

**Comment by NIRVANALAN** [comment]
thank  you.
